export { useGetTagsQuery } from "./useGetTagsQuery";
export { useCheckAuthQuery } from "./useCheckAuthQuery";
export { useLoginMutation } from "./useLoginMutation";
export { useLogoutMutation } from "./useLogoutMutation";
export { useRegisterMutation } from "./useRegisterMutation";
export { useGetUniversitiesQuery } from "./useGetUniversitiesQuery";
export { useGetGuildsMutation } from "./useGetGuildsMutation";
export { useGetGuildQuery } from "./useGetGuildQuery";
export { usePostContentMutation } from "./usePostContentMutation";
export { MutationKey, QueryId } from "./keys";
