export const Path = {
  Login: "/users/login",
  Logout: "/users/logout",
  Register: "/users/register",
  Identify: "/users/whoami",
  Universities: "/institutions/universities",
  Guilds: "/institutions/guilds",
  InstitutionImage: "/files/institution",
  TagImage: "/files/tag",
  ContentImage: "/files/image",
  ContentClip: "/files/clip",
  Tags: "/tags",
  GetContent: "/content",
  RateContent: "/content/rate",
};
